server:
  port: 8080
spring:
  mvc:
    path match:
      matching-strategy: path_pattern_parser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jdyy
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB #最大文件大小
      max-request-size: 40MB #最大请求大小
  # Redis
  redis:
    port: 6379
    host: localhost
    timeout: 3000
    password: 123456
    database: 2
  main:
    #    解决升级Spring Boot2.6后,因依赖循环引用导致启动时报错的问题
    allow-circular-references: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)不能加横杠("-")血的教训，修bug到吐血 T_T
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid

#swagger
springfox:
  documentation:
    swagger-ui:
      enabled: true # swagger 开启文档显示
#swagger美化
knife4j:
  enable: true # 开启增强
  production: false #生产模式
  basic:
    enable: false # 是否登录
    username: admin
    password: 123456